version: 'version'

services:
  frontend_nginx:
    image: myjob-frontend-nginx
    container_name: myjob-frontend-nginx-container
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - REACT_APP_MYJOB_SERVER_CLIENT_ID=${REACT_APP_MYJOB_SERVER_CLIENT_ID}
      - REACT_APP_MYJOB_SERVER_CLIENT_SECRECT=${REACT_APP_MYJOB_SERVER_CLIENT_SECRECT}
      - REACT_APP_FACEBOOK_CLIENT_ID=${REACT_APP_FACEBOOK_CLIENT_ID}
      - REACT_APP_FACEBOOK_CLIENT_SECRET=${REACT_APP_FACEBOOK_CLIENT_SECRET}
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_GOOGLE_CLIENT_SECRET=${REACT_APP_GOOGLE_CLIENT_SECRET}
      - REACT_APP_GOONGAPI_KEY=${REACT_APP_GOONGAPI_KEY}
      - REACT_APP_GOONGAPI_ACCESS_TOKEN=${REACT_APP_GOONGAPI_ACCESS_TOKEN}
      - REACT_APP_BING_MAPS_KEY=${REACT_APP_BING_MAPS_KEY}
      - REACT_APP_CHAT_APP_ID=${REACT_APP_CHAT_APP_ID}
      - REACT_APP_JOB_SEEKER_BOT_ID=${REACT_APP_JOB_SEEKER_BOT_ID}
      - REACT_APP_EMPLOYER_BOT_ID=${REACT_APP_EMPLOYER_BOT_ID}
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
      - REACT_APP_FIREBASE_DATABASE_URL=${REACT_APP_FIREBASE_DATABASE_URL}
    networks:
      - myjob-frontend-network
    ports:
      - "80:80"
    expose:
      - 80

networks:
  myjob-frontend-network:
    name: myjob-frontend-network