version: '3.8'

services:
  frontend_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: myjob-frontend-container
    volumes:
      - .:/myjob_web_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - myjob-network

  frontend_nginx:
    image: nginx:1.24.0-alpine
    container_name: myjob-frontend-nginx-container
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - myjob-network
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/hosts:/etc/hosts:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend_dev

networks:
  myjob-network:
    name: myjob-network